spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5434/product_ecommerce_db
    username: product_admin
    password: 1234
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/ecommerce

server:
  port: 8081
